#!/usr/bin/env ruby
# Выставляет у экрана входа такой же фон, как в текущией системе

current = `gsettings get org.gnome.desktop.background picture-uri`.strip
current.sub! 'file://', ''

puts "Wallpaper: #{current}"

system = "/usr/share/backgrounds/#{ENV['USER']}-background"
`sudo cp #{current} #{system}`

config = '/etc/lightdm/unity-greeter.conf'

puts "sudo sed -i -e \"s/^background=.*$/background=#{system.gsub('/', '\/')}/" #{config}"
`sudo sed -i -e "s/^background=.*$/background=#{system.gsub('/', '\/')}/" #{config}`
