#!/usr/bin/env ruby

def read(prop)
  `cat /sys/class/backlight/intel_backlight/#{prop}`.strip.to_i
end

def write(prop, value)
  `echo #{value} >> /sys/class/backlight/intel_backlight/#{prop}`
end

def step(current)
  if current > 800
    800
  else
    current / 2
  end
end

min     = 20
max     = read 'max_brightness'
current = read 'brightness'

diff    = ARGV.first
if diff == 'up'
  diff = step(current)
elsif diff == 'down'
  diff = -step(current)
else
  diff = diff.to_i
end

changed = current + diff
changed = min if changed < min
changed = max if changed > max

write 'brightness', changed
puts read 'brightness'
