#!/bin/bash
# Clean all bits to secure delete files (use twice for real secure data).

df -h $1

echo 'Is it REALLY this disk? [yN]'
read answer
case $answer in
    y)
        sudo dd if=/dev/urandom of=$1 bs=1M & pid=$!
        while sudo kill -USR1 $pid; do sleep 10; done
    ;;
esac
