#!/usr/bin/env ruby
# Создаёт новую тему (добавляя к имени префикс), заменяя в ней обою на ту, что
# сейчас установлена у пользователя.

DIR = '/usr/share/gdm/themes'

if 0 == ARGV.length or '-h' == ARGV.first or '--help' == ARGV.first
  puts 'Использование: gdm_with_my_wallpaper GDM-тема [префикс]'
  puts 'Создаёт новую тему, с обоей, что установлена у пользователя.'
  puts 'К имени новой темы добавляется префикс (по умолчанию, имя пользователя).'
  puts 'Если тема с новым именем уже существует, то она удаляется.'
  exit
end

OLD_THEME = ARGV[0]
NEW_THEME = OLD_THEME + (ARGV[1] or '-' + ENV['USER'])
WALLPAPER = `gconftool-2 --get /desktop/gnome/background/picture_filename`.strip

OLD_DIR = File.join(DIR, OLD_THEME)
NEW_DIR = File.join(DIR, NEW_THEME)

WALLPAPER_EXT = File.extname(WALLPAPER)

unless File.directory? OLD_DIR
  puts "Ошибка: темы #{OLD_THEME} не существует."
  exit
end

`sudo rm -R #{NEW_DIR}` if File.exists? NEW_DIR
`sudo cp -R #{OLD_DIR} #{NEW_DIR}`
`sudo cp "#{WALLPAPER}" #{File.join(NEW_DIR, 'background' + WALLPAPER_EXT)}`

require 'tempfile'
def rewrite(file, &block)
  content = File.read(file)
  content = yield(content)
  temp = Tempfile.new(File.basename(file))
  temp.puts content
  temp.close
  `sudo rm #{file}`
  `sudo cp #{temp.path} #{file}`
  `sudo chmod a+r #{file}`
  temp.delete
end

greeter = nil
rewrite File.join(NEW_DIR, 'GdmGreeterTheme.desktop') do |theme|
  greeter = theme.match(/Greeter\s*=\s*([^\n]+)\n/)[1]
  
  theme.sub! /Name\s*=\s*([^\n]+)\n/, "Name=\\1 with #{ENV['USER']} wallpaper\n"
  theme.sub! /Author\s*=\s*([^\n]*[^\n\.])\.?\n/, "Author=\\1, #{ENV['USER']}.\n"
end

rewrite File.join(NEW_DIR, greeter) do |content|
  regexp = /<item [^>]*background="true"[^>]*>.*? file="([^"]+)".*?<\/item>/m
  
  file = File.join(NEW_DIR, content.match(regexp)[1])
  `sudo rm #{file}`
  
  content.sub! regexp, '<item type="pixmap" id="background" background="true">
		<normal file="background' + WALLPAPER_EXT + '" />
		<pos anchor="c" x="50%" y="50%" width="100%" height="scale" />
	</item>'
  content
end
