#!/bin/sh
# Работа с личной папкой.

STORE=$HOME/.Личное
LINK=$HOME/Рабочий\ стол/Личное

if [ -e "$LINK" ]; then
    # Прячем
    fusermount -u "$LINK"
    rm -R "$LINK"
else
    # Показываем
    mkdir "$LINK"
    encfs "$STORE" "$LINK" --extpass "zenity --password"
    nautilus "$LINK"
fi
