#!/bin/sh

mkdir -p ~/.config/micro
mkdir -p ~/.config/bat
mkdir -p ~/.config/git

cp -f ~/dotfiles/zshrc ~/.zshrc
cp -f ~/dotfiles/gitconfig ~/.gitconfig
cp -f ~/dotfiles/ripgreprc ~/.ripgreprc
cp -f ~/dotfiles/micro.json ~/.config/micro/settings.json
cp -f ~/dotfiles/batconfig ~/.config/bat/config
cp -f ~/dotfiles/gitignore ~/.config/git/ignore
cp -f ~/dotfiles/starship.toml ~/.config/starship.toml
sed -i '/^\s*\$username\\/d;/^\s*\$hostname\\/d' ~/.config/starship.toml

mkdir -p ~/.ssh
chmod 700 ~/.ssh
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDwZrgt8W9uGndgD2aoMOjN0lhvFYsYzfietr5gu5lUV andrey@sitnik.ru" > ~/.ssh/authorized_keys
chmod 644 ~/.ssh/authorized_keys

if command -v micro >/dev/null 2>&1; then
  micro -plugin install editorconfig
fi

mkdir -p ~/.local/share/history/
touch ~/.local/share/history/histfile
mkdir -p ~/.local/bin

curl -sL https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz | tar xz
chmod +x eza
mv eza ~/.local/bin

curl -sL https://github.com/Wilfred/difftastic/releases/download/0.63.0/difft-x86_64-unknown-linux-gnu.tar.gz | tar xz
chmod +x difft
mv difft ~/.local/bin

curl -sL https://github.com/sharkdp/bat/releases/download/v0.25.0/bat-v0.25.0-x86_64-unknown-linux-gnu.tar.gz | tar xz --strip-components=1 bat-v0.25.0-x86_64-unknown-linux-gnu/bat
chmod +x bat
mv bat ~/.local/bin

curl -sL https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz | tar xz --strip-components=1 ripgrep-14.1.1-x86_64-unknown-linux-musl/rg
chmod +x rg
mv rg ~/.local/bin

curl -sL https://github.com/atuinsh/atuin/releases/download/v18.6.1/atuin-x86_64-unknown-linux-gnu.tar.gz | tar xz --strip-components=1 atuin-x86_64-unknown-linux-gnu/atuin
chmod +x atuin
mv atuin ~/.local/bin

curl -sS https://starship.rs/install.sh > starship.sh
chmod a+x starship.sh
./starship.sh -y -b ~/.local/bin
rm starship.sh

mkdir -p ~/.local/lib/zsh
if command -v git >/dev/null 2>&1 && command -v zsh >/dev/null 2>&1; then
  git clone -q https://github.com/zsh-users/zsh-syntax-highlighting \
    ~/.local/lib/zsh/zsh-syntax-highlighting
  git clone https://github.com/zsh-users/zsh-autosuggestions \
    ~/.local/lib/zsh/zsh-autosuggestions
  git clone https://github.com/jimhester/per-directory-history \
    ~/.local/lib/zsh/per-directory-history
  mkdir -p ~/.local/lib/zsh/pnpm-shell-completion
  pnpm_url=$(curl -s \
    https://api.github.com/repos/g-plane/pnpm-shell-completion/releases/latest \
    | grep "browser_download_url.*pnpm-shell-completion_x86_64-unknown-linux-gnu.tar.gz" \
    | cut -d '"' -f 4)
  curl -sSL $pnpm_url > ~/pnpm-completion.tar.gz
  tar -xzf ~/pnpm-completion.tar.gz \
    -C ~/.local/lib/zsh/pnpm-shell-completion \
    pnpm-shell-completion pnpm-shell-completion.plugin.zsh
  chmod a+x ~/.local/lib/zsh/pnpm-shell-completion/pnpm-shell-completion
  rm ~/pnpm-completion.tar.gz
fi
