#!/bin/bash

cp ../gitconfig ~/.gitconfig
cp ../ripgreprc ~/.ripgreprc
cp ../micro.~me/ai/.config/micro/settings.json
cp ../batconfig ~/.config/bat/config
cp ../starship.toml ~/.config/starship.toml
cp ../zshrc ~/.zshrc
cp ../gitignore ~/.config/git/ignore

if command -v micro >/dev/null 2>&1; then
  micro -plugin install editorconfig
fi

if command -v git >/dev/null 2>&1 && command -v zsh >/dev/null 2>&1; then
  git clone -q https://github.com/zsh-users/zsh-syntax-highlighting \
    ~/.zsh/zsh-syntax-highlighting
  git clone -q https://github.com/zsh-users/zsh-history-substring-search \
    ~/.zsh/zsh-history-substring-search
fi
