#!/bin/bash

project_hooks=$(git config get --local core.hooksPath)
if [ -n "$project_hooks" ] && [ -d "$project_hooks" ]; then
  if [ -x "$project_hooks/pre-push" ]; then
    /home/ai/Dev/environment/bin/dev CI=1 $project_hooks/pre-push
  fi
fi
