#!/bin/bash

project_hooks=$(git config get --local core.hooksPath)
if [ -n "$project_hooks" ] && [ -d "$project_hooks" ]; then
  if [ -x "$project_hooks/pre-applypatch" ]; then
    /home/ai/Dev/environment/bin/dev $project_hooks/pre-applypatch
  fi
fi
